export const TopHoldemData = [
  {
    place: "1",
    voucher: "-",
    prize: "A კატეგორიის საგზური",
    icon: process.env.PUBLIC_URL + "/assets/travel-icon-sm.png",
  },
  {
    place: "2",
    voucher: "-",
    prize: "B კატეგორიის საგზური",
    icon: process.env.PUBLIC_URL + "/assets/ticket-icon-sm.png",
  },
  { place: "3", voucher: "1 500 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "4", voucher: "1 200 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "5", voucher: "1000 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "6", voucher: "800 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "7", voucher: "500 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "8", voucher: "500 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "9", voucher: "500 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "11", voucher: "500 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "12", voucher: "500 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "13", voucher: "500 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "14", voucher: "500 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "15", voucher: "450 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "16", voucher: "450 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "17", voucher: "450 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "18", voucher: "400 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "19", voucher: "400 ₾", prize: "სპეც. ტურნირის ბილეთი" },
  { place: "20", voucher: "400 ₾", prize: "სპეც. ტურნირის ბილეთი" },
];
